version: "3.8"

services:
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  mock-api:
    build: ./mock-api
    volumes:
      - ./mock-api:/app
    ports:
      - 8000:8000

  queue-api:
    build: ./queue-api
    volumes:
      - ./queue-api:/app
    environment:
      REDIS_URL: redis:6379
    ports:
      - 3000:3000
    depends_on:
      - redis

  fetch-service-1:
    build: ./fetch-service
    volumes:
      - ./fetch-service:/app
    environment:
      REDIS_URL: redis:6379
      MOCK_API_URL: mock-api:8000
      QUEUE_API_URL: queue-api:3000
    depends_on:
      - redis
      - mock-api
      - queue-api

  fetch-service-2:
    build: ./fetch-service
    volumes:
      - ./fetch-service:/app
    environment:
      REDIS_URL: redis:6379
      MOCK_API_URL: mock-api:8000
      QUEUE_API_URL: queue-api:3000
    depends_on:
      - redis
      - mock-api
      - queue-api

  fetch-service-3:
    build: ./fetch-service
    volumes:
      - ./fetch-service:/app
    environment:
      REDIS_URL: redis:6379
      MOCK_API_URL: mock-api:8000
      QUEUE_API_URL: queue-api:3000
    depends_on:
      - redis
      - mock-api
      - queue-api

  average-compute-service:
    build: ./average-compute-service
    volumes:
      - ./average-compute-service:/app
    environment:
      REDIS_URL: redis:6379
      QUEUE_API_URL: queue-api:3000
    depends_on:
      - redis
      - mock-api
      - queue-api
