version: "3.8"

services:
  mock-api:
    build: ./mock-api
    volumes:
      - ./mock-api:/app
    ports:
      - "8000:8000"

  fetch-service:
    build: ./fetch-service
    volumes:
      - ./fetch-service:/app
    ports:
      - "3000:3000"
